### ISSUE TITLE
Messages are not in date order

### ISSUE THREAD

**Issue by brandoncurtis** [hfaran/slack2html#1]
Successful conversion of JSON to HTML, but some messages from seven months ago are showing up at the bottom of the HTML, below new messages from today.  

JSON-to-HTML conversion using the [original levels.io PHP script](https://gist.github.com/levelsio/122907e95956602e5c09) on the same Slack export file does not have this problem.

**Comment by brandoncurtis** [comment]
This is due to a problem in the underlying `slack-export-viewer` caused by the OS-dependent behavior of `os.listdir()`.  Fixed by hfaran/slack-export-viewer#25.

**Comment by hfaran** [comment]
Resolved by https://github.com/hfaran/slack-export-viewer/pull/25
